# 7.11 Views: Shallow Copies

The array method **view** returns a new array object with a view of the original array object's data.

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.view()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
id(numbers)

2472694249792

In [7]:
id(numbers2)

2472698703920

In [8]:
numbers[1] *= 10

In [9]:
numbers2

array([ 1, 20,  3,  4,  5])

In [10]:
numbers

array([ 1, 20,  3,  4,  5])

In [11]:
numbers2[1] /= 10

In [12]:
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers2

array([1, 2, 3, 4, 5])

### Slice Views

Slices also create views.

In [14]:
numbers2 = numbers[0:3]

In [15]:
numbers2

array([1, 2, 3])

In [16]:
id(numbers)

2472694249792

In [17]:
id(numbers2)

2472698802624

We can confirm that numbers2 is a view of only the first three numbers elements by attempting to access numbers2[3], which produces an IndexError:

In [18]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [19]:
numbers[1] *= 20

In [20]:
numbers

array([ 1, 40,  3,  4,  5])

In [21]:
numbers2

array([ 1, 40,  3])