# 7.12 Deep Copies

The **array method copy** returns a new array object with a deep copy of the original array object's data. First, let's create an array and a deep copy of that array:

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.copy()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
numbers[1] *= 10

In [7]:
numbers

array([ 1, 20,  3,  4,  5])

In [8]:
numbers2

array([1, 2, 3, 4, 5])

### Module copy -- Shallow vs. Deep Copies for Other Types of Python Objects

In previous chapters, we covered shallow copying. In this chapter, we've covered how to deep copy array objects using their copy method. If you need deep copies of other types of Python objects, pass them to the **copy** module's **deepcopy** function.