# 7.13 Reshaping and Transposing

### reshape vs. resize

The array methods reshape and resize both enable you to change an array's dimensions.
Method reshape returns a view (shallow copy) of the original array with the new dimensions. It does not modify the original array:

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70],[100, 87, 90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [4]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [6]:
grades.resize(1, 6)

In [7]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

### flatten vs. ravel

You can take a multidimensional array and flatten it into a single dimension with the methods **flatten** and **ravel**. Method flatten deep copies the original array's data:

In [8]:
grades = np.array([[87, 96, 70],[100, 87, 90]])

In [9]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [10]:
flattened = grades.flatten()

In [11]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [12]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [13]:
flattened[0] = 100

In [14]:
flattened

array([100,  96,  70, 100,  87,  90])

In [15]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Method ravel produces a view of the original array, which shares the grades array's data:

In [16]:
raveled = grades.ravel()

In [17]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [18]:
raveled[0] = 100

In [19]:
raveled

array([100,  96,  70, 100,  87,  90])

In [20]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Transposing Rows and Columns

The **T attribute** returns a transposed view (shallow copy) of the array.

In [21]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

Transposing does *not* modify the original array

In [22]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Horizontal and Vertical Stacking

You can combine arrays by adding more columns or more rows --known as *horizontal stacking* and *vertical stacking*.

In [23]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

Let's assume grades2 represents three additional exam grades for the two students in the grades array. We can combine grades and grades2 with NumPy's **hstack function** by passing a tuple containing the arrays to combine. The extra parentheses are required because hstack expects one argument:

In [24]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

Next, let's assume that grades2 repesents two more students' grades on three examns. In this case, we can combine grades and grades2 with NumPy's **vstack function**:

In [25]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])