# 7.8 NumPy Calculation Methods

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [4]:
grades.sum()

1054

In [5]:
grades.min()

70

In [9]:
grades.max()

100

In [10]:
grades.mean()

87.83333333333333

In [7]:
grades.std() # standard deviation

8.792357792739987

In [8]:
grades.var() # variance

77.30555555555556

### Calculations by Row Column

Specifying axis=0 performs the calculation on all the row values within each column:

In [12]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [13]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])